### ISSUE TITLE
invalid zip file

### ISSUE THREAD

**Issue by bdeboe** [mx-alex/mx#3]
Hi,
when trying to open the zipfile, it's complaining the zipped folder is invalid. I'm getting the error both when using Windows' built-in zip support or when using 7-zip.
Thanks,
benjamin

**Comment by mx-alex** [comment]
Hi benjamin,
I download and tested this zip ( see attachment)
All is ok
Try it

Your Microsoft Excel is ok ?
========
Alex


 
----- Reply to message -----
Subject: [mx-alex/mx] invalid zip file (Issue #3)
Date: Thu, 7 Apr 2022, 13:09
From:  Benjamin De Boe ***@***.***>
To:  mx-alex/mx ***@***.***>


 

Hi,
when trying to open the zipfile, it's complaining the zipped folder is invalid. I'm getting the error both when using Windows' built-in zip support or when using 7-zip.
Thanks,
benjamin

**Comment by bdeboe** [comment]
trying the download again solved it, but I had misread the instructions altogether and didn't even need it for that first setup step. I have it all working now. Thanks for the quick response!
